apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c6kbxrt6b-python
  janus-idp.io/tekton: c6kbxrt6b-python
  backstage.io/kubernetes-id: c6kbxrt6b-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c6kbxrt6b-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
